# Generated by Django 4.2.4 on 2023-08-13 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_groups_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
